version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
  sonarqube:
    image: 'sonarqube:lts'
    ports:
      - '9000:9000'
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'
  nexus3:
    image: sonatype/nexus3
    ports:
      - '8081:8081'
    volumes:
      - 'nexus-data:/nexus-data'
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    # command: mysql -e "create user IF NOT EXISTS 'devops'@'%' identified by 'mestre';" 
    # command: mysql -e "create user IF NOT EXISTS 'devops_dev'@'%' identified by 'mestre';"  
    # command: mysql -e "create database IF NOT EXISTS todo;" 
    # command: mysql -e "create database IF NOT EXISTS todo_dev;" 
    # command: mysql -e "create database IF NOT EXISTS test_todo_dev;"
    # command: mysql -e "grant all privileges on *.* to devops@'%' identified by 'mestre';" 
    # command: mysql -e "grant all privileges on *.* to devops_dev@'%' identified by 'mestre';"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mestre
      # - MYSQL_DATABASE=todo_dev
      # - MYSQL_USER=devops_dev
      # - MYSQL_PASSWORD=mestre
    ports:
      - '3306:3306'
    volumes:
      - 'my-db:/var/lib/mysql'
volumes:
  jenkins_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_conf:
    driver: local
  sonarqube_extensions:
    driver: local
  nexus-data:
    driver: local
  my-db:
    driver: local
