version: '3'

services:
    mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=petclinic
        # - MYSQL_DATABASE=petclinic
      volumes:
        # - "./conf.d:/etc/mysql/conf.d:ro"
        - "./dump:/docker-entrypoint-initdb.d"

    petclinic:    
      image: sandinoandroid/spring-petclinic:task1
      depends_on:
      - mysql
      ports:
        - 8080:8080

